{% set name = "sciencebasepy" %}
{% set version = "2.0.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sciencebasepy-{{ version }}.tar.gz
  sha256: 620523ad9a2aa4f563fd2664453e5e20096d09a9d0fde7e793afb58ac62b7224

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=61.0
    - pip
  run:
    - python >=3.7
    - requests
    - requests-mock
    - progress
    - pytest
    - charset-normalizer

test:
  imports:
    - sb3
    - sciencebasepy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://code.usgs.gov/sas/sdm/sciencebasepy
  summary: Python ScienceBase Utilities
  license: MPL-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ocefpaf
