{% set name = "sciencebasepy" %}
{% set version = "2.0.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sciencebasepy-{{ version }}.tar.gz
  sha256: fb878b22ef8dd37c7f89f373140fe1c1b82d6ae59b6b67020bb745f436244d18

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - requests
    - requests-mock
    - progress
    - pytest
    - charset-normalizer

test:
  imports:
    - sb3
    - sciencebasepy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://code.usgs.gov/sas/sdm/sciencebasepy
  summary: Python ScienceBase Utilities
  license: MPL-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ocefpaf
